# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

# Makefile for testing complete CPU

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../cpu_core/nicnac16_cpu.v
VERILOG_SOURCES += $(PWD)/../cpu_core/datapath/datapath.v
VERILOG_SOURCES += $(PWD)/../cpu_core/control/control_unit.v
VERILOG_SOURCES += $(PWD)/../cpu_core/control/system_timing.v
VERILOG_SOURCES += $(PWD)/../cpu_core/memory/*.v
VERILOG_SOURCES += $(PWD)/../cpu_core/alu/*.v
VERILOG_SOURCES += $(PWD)/../cpu_core/components/*.v

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = nicnac16_cpu

# MODULE is the basename of the Python test file
MODULE = test_cpu_integration

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim