# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

# Makefile for testing datapath

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../../../rtl/core/cpu/datapath/datapath.v
VERILOG_SOURCES += $(PWD)/../../../rtl/core/cpu/alu/*.v
VERILOG_SOURCES += $(PWD)/../../../rtl/core/cpu/components/*.v

# TOPLEVEL is the name of the toplevel module in your Verilog or VERILOG file
TOPLEVEL = datapath

# MODULE is the basename of the Python test file
MODULE = test_datapath

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim