# This file is public domain, it can be freely copied without restrictions.
# SPDX-License-Identifier: CC0-1.0

# Makefile for testing control_unit

# defaults
SIM ?= icarus
TOPLEVEL_LANG ?= verilog

VERILOG_SOURCES += $(PWD)/../cpu_core/control/control_unit.v
VERILOG_SOURCES += $(PWD)/../cpu_core/control/system_timing.v  
VERILOG_SOURCES += $(PWD)/../cpu_core/control/timing_ring_counter.v
VERILOG_SOURCES += $(PWD)/../cpu_core/components/*.v

# TOPLEVEL is the name of the toplevel module in your Verilog or VHDL file
TOPLEVEL = control_unit

# MODULE is the basename of the Python test file
MODULE = test_control_unit

# include cocotb's make rules to take care of the simulator setup
include $(shell cocotb-config --makefiles)/Makefile.sim